<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Enums;

class BookingEntryEnum
{
    const C_CREDIT = 'CREDIT';
    const C_DEBIT = 'DEBIT';
}
