<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Enums;

class FeeTypeEnum
{
    const C_BELOW_STANDARD_FEE = 'BELOW_STANDARD_FEE';
    const C_BELOW_STANDARD_SHIPPING_FEE = 'BELOW_STANDARD_SHIPPING_FEE';
    const C_FINAL_VALUE_FEE_FIXED_PER_ORDER = 'FINAL_VALUE_FEE_FIXED_PER_ORDER';
    const C_FINAL_VALUE_FEE  = 'FINAL_VALUE_FEE';
    const C_INTERNATIONAL_FEE = 'INTERNATIONAL_FEE';
    const C_HIGH_ITEM_NOT_AS_DESCRIBED_FEE = 'HIGH_ITEM_NOT_AS_DESCRIBED_FEE';
    const C_HIGH_ITEM_NOT_AS_DESCRIBED_SHIPPING_FEE = 'HIGH_ITEM_NOT_AS_DESCRIBED_SHIPPING_FEE';
    const C_PAYMENT_PROCESSING_FEE = 'PAYMENT_PROCESSING_FEE';
    const C_FINAL_VALUE_SHIPPING_FEE = 'FINAL_VALUE_SHIPPING_FEE';
    const C_OTHER_FEES  = 'OTHER_FEES';
}
