<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Enums;

class PayoutStatusEnum
{
    const C_INITIATED = 'INITIATED';
    const C_SUCCEEDED = 'SUCCEEDED';
    const C_REVERSED = 'REVERSED';
    const C_RETRYABLE_FAILED  = 'RETRYABLE_FAILED';
    const C_TERMINAL_FAILED = 'TERMINAL_FAILED';
}
