<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Enums;

class TransactionTypeEnum
{
    const C_SALE = 'SALE';
    const C_REFUND = 'REFUND';
    const C_CREDIT = 'CREDIT';
    const C_DISPUTE  = 'DISPUTE';
    const C_SHIPPING_LABEL = 'SHIPPING_LABEL';
    const C_TRANSFER = 'TRANSFER';
    const C_NON_SALE_CHARGE = 'NONE_SALE_CHARGE';
}
