<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Enums;

class TransactionStatusEnum
{
    const C_FUNDS_ON_HOLD = 'FUNDS_ON_HOLD';
    const C_FUNDS_PROCESSING = 'FUNDS_PROCESSING';
    const C_FUNDS_AVAILABLE_FOR_PAYOUT = 'FUNDS_AVAILABLE_FOR_PAYOUT';
    const C_PAYOUT  = 'PAYOUT';
    const C_COMPLETED = 'COMPLETED';
    const C_FAILED = 'FAILED';
}
