<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Negotiation\Enums;

class OfferTypeEnum
{
    const C_SELLER_INITIATED_OFFER = 'SELLER_INITIATED_OFFER';
}
