<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Negotiation\Enums;

class OfferStatusEnum
{
    const C_PENDING = 'PENDING';
    const C_RETRACTED = 'RETRACTED';
    const C_EXPIRED = 'EXPIRED';
    const C_CANCELLED = 'CANCELLED';
    const C_COUNTERED = 'COUNTERED';
    const C_DECLINED = 'DECLINED';
    const C_AUTO_DECLINED = 'AUTO_DECLINED';
    const C_AUTO_ACCEPTED = 'AUTO_ACCEPTED';
    const C_ACCEPTED = 'ACCEPTED';
}
