<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Services;

class FinanceService extends \DTS\eBaySDK\Finance\Services\FinanceBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'GetPayout' => [
            'method' => 'GET',
            'resource' => 'payout',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetPayoutRestResponse',
            'params' => [
                'payout_id' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],
        'GetPayouts' => [
            'method' => 'GET',
            'resource' => 'payout',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetPayoutsRestResponse',
            'params' => [
                'limit' => [
                    'valid' => ['int'],
                    'required' => false
                ],
                'offset' => [
                    'valid' => ['int'],
                    'required' => false
                ],
                'filter' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
                'sort' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
            ]
        ],
        'GetPayoutSummary' => [
            'method' => 'GET',
            'resource' => 'payout_summary',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetPayoutsSummaryRestResponse',
            'params' => [
                'filter' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
            ]
        ],
        'GetTransactions' => [
            'method' => 'GET',
            'resource' => 'transaction',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetTransactionsRestResponse',
            'params' => [
                'limit' => [
                    'valid' => ['int'],
                    'required' => false
                ],
                'offset' => [
                    'valid' => ['int'],
                    'required' => false
                ],
                'filter' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
                'sort' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
            ]
        ],
        'GetTransactionSummary' => [
            'method' => 'GET',
            'resource' => 'transaction_summary',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestResponse',
            'params' => [
                'filter' => [
                    'valid' => ['string'],
                    'required' => false,
                ],
            ]
        ],
        'GetSellerFundsSummary' => [
            'method' => 'GET',
            'resource' => 'seller_funds_summary',
            'responseClass' => '\DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestResponse',
            'params' => [
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetPayoutRestResponse
     */
    public function getPayout(\DTS\eBaySDK\Finance\Types\GetPayoutRestRequest $request)
    {
        return $this->getPayoutAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutAsync(\DTS\eBaySDK\Finance\Types\GetPayoutRestRequest $request)
    {
        return $this->callOperationAsync('GetPayout', $request);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutsRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetPayoutsRestResponse
     */
    public function getPayouts(\DTS\eBaySDK\Finance\Types\GetPayoutsRestRequest $request)
    {
        return $this->getPayoutsAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutsAsync(\DTS\eBaySDK\Finance\Types\GetPayoutsRestRequest $request)
    {
        return $this->callOperationAsync('GetPayouts', $request);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutSummaryRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetPayoutSummaryRestResponse
     */
    public function getPayoutSummary(\DTS\eBaySDK\Finance\Types\GetPayoutSummaryRestRequest $request)
    {
        return $this->getPayoutSummaryAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetPayoutSummaryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutSummaryAsync(\DTS\eBaySDK\Finance\Types\GetPayoutSummaryRestRequest $request)
    {
        return $this->callOperationAsync('GetPayoutSummary', $request);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetTransactionsRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetTransactionsRestResponse
     */
    public function getTransactions(\DTS\eBaySDK\Finance\Types\GetTransactionsRestRequest $request)
    {
        return $this->getTransactionsAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetTransactionsRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionsAsync(\DTS\eBaySDK\Finance\Types\GetTransactionsRestRequest $request)
    {
        return $this->callOperationAsync('GetTransactions', $request);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestResponse
     */
    public function getTransactionSummary(\DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestRequest $request)
    {
        return $this->getTransactionSummaryAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionSummaryAsync(\DTS\eBaySDK\Finance\Types\GetTransactionSummaryRestRequest $request)
    {
        return $this->callOperationAsync('GetTransactionSummary', $request);
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestRequest $request
     * @return \DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestResponse
     */
    public function getSellerFundsSummary(\DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestRequest $request)
    {
         return $this->getSellerFundsSummaryAsync($request)->wait();
    }

    /**
     * @param \DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSellerFundsSummaryAsync(\DTS\eBaySDK\Finance\Types\GetSellerFundsSummaryRestRequest $request)
    {
        return $this->callOperationAsync('GetSellerFundsSummary', $request);
    }
}
