<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finance\Types;

/**
 *
 * @property integer $limit
 * @property integer $offset
 * @property \DTS\eBaySDK\Finance\Types\FilterField[] $filter
 * @property \DTS\eBaySDK\Finance\Types\SortField[] $sort
 */
class PayoutsRestRequest extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'limit' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'limit'
        ],
        'offset' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'offset'
        ],
        'filter' => [
            'type' => 'DTS\eBaySDK\Finance\Types\FilterField',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'filter'
        ],
        'sort' => [
            'type' => 'DTS\eBaySDK\Finance\Types\SortField',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'sort'
        ],
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
