<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Negotiation\Enums;

class TimeDurationUnitEnum
{
    const C_YEAR = 'YEAR';
    const C_MONTH = 'MONTH';
    const C_DAY = 'DAY';
    const C_HOUR = 'HOUR';
    const C_CALENDAR_DAY = 'CALENDAR_DAY';
    const C_BUSINESS_DAY = 'BUSINESS_DAY';
    const C_MINUTE = 'MINUTE';
    const C_SECOND = 'SECOND';
    const C_MILLISECOND = 'MILLISECOND';
}
